### PR TITLE
How I think annotator should be handled.

### PR DESCRIPTION
**Pull request by hsorby**

### CODE REVIEW

**Comment by agarny** [comment]
@hsorby, I have merged the `main` branch in https://github.com/cellml/libcellml/pull/836, which means that your PR now has conflicts. Could please resolve them? Alternatively, I can go through each of your commits in this PR and apply them to https://github.com/cellml/libcellml/pull/836. Just let me know.

**Comment by hsorby** [comment]
I'll have a look.

**Comment by hsorby** [comment]
We can't rename `Unit` to `UNITS_ITEM`.  The `CellmlElementType` is a direct relationship to the XML elements defined in the specification.

**Comment by agarny** [comment]
> We can't rename `UNIT` to `UNITS_ITEM`.  The `CellmlElementType` is a direct relationship to the XML elements defined in the specification.

Argh, ok, going to revert that commit. :/

**Pull request merged**
